import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783707752717 implements MigrationInterface {
    name = '1712054900000InitialSchema1783707752717'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
        await queryRunner.query(`CREATE TABLE "membership_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying, "level" integer NOT NULL DEFAULT '0', "yearlyFee" integer NOT NULL, "minYearsExperience" integer NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1542799bf69f01c12646f423c46" UNIQUE ("name"), CONSTRAINT "UQ_8102f274cba750f14764ec3b577" UNIQUE ("code"), CONSTRAINT "PK_8161e16b6dee6e59b58fbec3e5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_title_enum" AS ENUM('Eng.', 'Dr.', 'Prof.', 'Mr.', 'Ms.', 'Mrs.')`);
        await queryRunner.query(`CREATE TYPE "public"."users_gender_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TYPE "public"."users_membershipclass_enum" AS ENUM('GRADUATE', 'ASSOCIATE', 'MIET', 'CORPORATE', 'SENIOR', 'FELLOW', 'HONORARY')`);
        await queryRunner.query(`CREATE TYPE "public"."users_membershipstatus_enum" AS ENUM('PENDING', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'REVOKED')`);
        await queryRunner.query(`CREATE TYPE "public"."users_engineeringdiscipline_enum" AS ENUM('Civil', 'Mechanical', 'Electrical', 'Electronics', 'Chemical', 'Mining', 'Agricultural', 'Environmental', 'Computer', 'Telecommunications', 'Petroleum', 'Biomedical', 'Industrial', 'Marine', 'Aeronautical', 'Other')`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('MEMBER', 'ADMIN', 'SUPER_ADMIN', 'REVIEWER', 'SECRETARIAT', 'EVALUATOR', 'MPDC', 'COUNCIL')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "email" character varying NOT NULL, "password" character varying NOT NULL, "emailVerified" boolean NOT NULL DEFAULT false, "emailVerificationCode" character varying, "emailVerificationExpiry" TIMESTAMP WITH TIME ZONE, "passwordResetToken" character varying, "passwordResetExpiry" TIMESTAMP WITH TIME ZONE, "twoFASecret" text, "enable2FA" boolean NOT NULL DEFAULT false, "refreshToken" text, "apiKey" text, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP WITH TIME ZONE, "loginOtpCode" character varying, "loginOtpExpiry" TIMESTAMP WITH TIME ZONE, "title" "public"."users_title_enum", "firstName" character varying, "middleName" character varying, "lastName" character varying, "gender" "public"."users_gender_enum", "dateOfBirth" date, "nationality" character varying, "phoneNumber" character varying, "profilePhotoUrl" character varying, "employer" character varying, "position" character varying, "location" character varying, "membershipId" character varying, "membershipClass" "public"."users_membershipclass_enum", "membershipCategoryId" uuid, "membershipStatus" "public"."users_membershipstatus_enum" NOT NULL DEFAULT 'PENDING', "engineeringDiscipline" "public"."users_engineeringdiscipline_enum", "joiningDate" date, "membershipExpiryDate" date, "annualMembershipFee" integer, "role" "public"."users_role_enum" NOT NULL DEFAULT 'MEMBER', "isActive" boolean NOT NULL DEFAULT true, "emailPreferences" jsonb NOT NULL DEFAULT '{}', "smsPreferences" jsonb NOT NULL DEFAULT '{}', "pushPreferences" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_5c3de66efa2ca583780ffedb90e" UNIQUE ("membershipId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e4aa9c0fec118f1c8a6edd309" ON "users" ("membershipCategoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e3d0240b49c40521aaeb95329" ON "users" ("phoneNumber") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_48054969958a2041d65fca2c1f" ON "users" ("membershipId") WHERE "membershipId" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "upgrade_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" uuid, "updatedBy" uuid, "fromCategoryId" uuid NOT NULL, "toCategoryId" uuid NOT NULL, "minYearsExperience" integer NOT NULL DEFAULT '0', "minCpdPoints" integer NOT NULL DEFAULT '0', "requiresActiveMembership" boolean NOT NULL DEFAULT true, "requiresNoPendingApplication" boolean NOT NULL DEFAULT true, "requiredDocuments" jsonb NOT NULL DEFAULT '[]', "requiresApproval" boolean NOT NULL DEFAULT true, "description" text, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0bcbe16ad48e8865217ab9075df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df14ec8f89f337a5416fa7f9c4" ON "upgrade_rules" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_b58b2cf38367f9fe31edd8ddc5" ON "upgrade_rules" ("toCategoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_30906b66cb1af7a9a0c91df1ff" ON "upgrade_rules" ("fromCategoryId") `);
        await queryRunner.query(`CREATE TYPE "public"."upgrade_applications_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "upgrade_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" uuid, "updatedBy" uuid, "userId" uuid NOT NULL, "fromCategoryId" uuid NOT NULL, "toCategoryId" uuid NOT NULL, "status" "public"."upgrade_applications_status_enum" NOT NULL DEFAULT 'PENDING', "submittedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "reviewedAt" TIMESTAMP WITH TIME ZONE, "reviewedById" uuid, "rejectionReason" text, "applicantNotes" text, CONSTRAINT "PK_b07101db846b6616cac7d6f3d2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c8a037f603d080132ca4a6019d" ON "upgrade_applications" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_96513ff83ebb6f15d30aaa4b52" ON "upgrade_applications" ("toCategoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f20db0bed145518e8fbd4eba5" ON "upgrade_applications" ("fromCategoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f145ea19883c1a2d2f015b67f9" ON "upgrade_applications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6185692b04b1557a7dae546045" ON "upgrade_applications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "registration_experiences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "registrationId" uuid NOT NULL, "employerName" character varying NOT NULL, "position" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date, "isCurrent" boolean NOT NULL DEFAULT false, "responsibilities" text, "location" character varying, "department" character varying, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_9d0d1d106db393dbc40139bfe3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a77dcf24eb60816939bd282bcd" ON "registration_experiences" ("registrationId") `);
        await queryRunner.query(`CREATE TABLE "engineering_institutions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "country" character varying NOT NULL DEFAULT 'Tanzania', "institutionType" character varying NOT NULL DEFAULT 'UNIVERSITY', "recognitionStatus" character varying NOT NULL DEFAULT 'RECOGNIZED', "isActive" boolean NOT NULL DEFAULT true, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_72b0840122f44c81745b0ca265d" UNIQUE ("name"), CONSTRAINT "PK_b6a6768c3c0658fadf8a6d9b6d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "registration_educations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "registrationId" uuid NOT NULL, "institutionId" uuid, "institutionName" character varying NOT NULL, "qualification" character varying NOT NULL, "fieldOfStudy" character varying, "startDate" date NOT NULL, "endDate" date, "grade" character varying, "location" character varying, "attachmentUrl" character varying, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_ab0676730978c8a2fbb6653172d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_60054d4846fde3cde29f4fbf45" ON "registration_educations" ("registrationId") `);
        await queryRunner.query(`CREATE TYPE "public"."registration_documents_documenttype_enum" AS ENUM('CV', 'CERTIFICATE', 'DEGREE', 'STATUTORY_BOARD', 'PROFILE_PHOTO', 'ADDITIONAL')`);
        await queryRunner.query(`CREATE TYPE "public"."registration_documents_status_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "registration_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "registrationId" uuid NOT NULL, "documentType" "public"."registration_documents_documenttype_enum" NOT NULL, "fileName" character varying NOT NULL, "fileUrl" character varying NOT NULL, "fileSize" integer NOT NULL, "mimeType" character varying NOT NULL, "description" text, "status" "public"."registration_documents_status_enum" NOT NULL DEFAULT 'PENDING', "verificationNotes" text, "verifiedBy" uuid, "verifiedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b7c0d11b37eb60171a8304833ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb3295a550bc5c23d0a9645663" ON "registration_documents" ("documentType") `);
        await queryRunner.query(`CREATE INDEX "IDX_11dfe2648f9819f117d0f516ae" ON "registration_documents" ("registrationId") `);
        await queryRunner.query(`CREATE TYPE "public"."registration_references_referencetype_enum" AS ENUM('PROPOSER', 'SUPPORTER')`);
        await queryRunner.query(`CREATE TABLE "registration_references" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "registrationId" uuid NOT NULL, "referenceType" "public"."registration_references_referencetype_enum" NOT NULL, "fullName" character varying NOT NULL, "membershipCategory" character varying NOT NULL, "membershipNumber" character varying NOT NULL, "knownFrom" date, "email" character varying, "phoneNumber" character varying, "organisation" character varying, "relationship" character varying, "verified" boolean NOT NULL DEFAULT false, "verifiedAt" TIMESTAMP WITH TIME ZONE, "verificationNotes" text, CONSTRAINT "PK_96c77583c879ebaf29d0bb98a46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9f002a1c325777ec374a11643" ON "registration_references" ("referenceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_40dbbc2643e52cbbf3a8a3bb11" ON "registration_references" ("registrationId") `);
        await queryRunner.query(`CREATE TYPE "public"."registrations_status_enum" AS ENUM('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED')`);
        await queryRunner.query(`CREATE TYPE "public"."registrations_currentstep_enum" AS ENUM('PERSONAL_DETAILS', 'REGISTRATION_DETAILS', 'EDUCATION_EXPERIENCE', 'REFERENCES', 'EMAIL_VERIFICATION', 'PAYMENT', 'DECLARATION')`);
        await queryRunner.query(`CREATE TYPE "public"."registrations_engineeringdiscipline_enum" AS ENUM('Civil', 'Mechanical', 'Electrical', 'Electronics', 'Chemical', 'Mining', 'Agricultural', 'Environmental', 'Computer', 'Telecommunications', 'Petroleum', 'Biomedical', 'Industrial', 'Marine', 'Aeronautical', 'Other')`);
        await queryRunner.query(`CREATE TYPE "public"."registrations_applicationtype_enum" AS ENUM('NEW', 'UPGRADING')`);
        await queryRunner.query(`CREATE TYPE "public"."registrations_registrationcategory_enum" AS ENUM('GRADUATE', 'STANDARD')`);
        await queryRunner.query(`CREATE TYPE "public"."registrations_reviewstage_enum" AS ENUM('SECRETARIAT_REVIEW', 'EVALUATOR_REVIEW', 'SECRETARIAT_EVALUATOR_RECOMMENDATION', 'MPDC_REVIEW', 'SECRETARIAT_MPDC_RECOMMENDATION', 'COUNCIL_REVIEW', 'SECRETARIAT_COUNCIL_RECOMMENDATION', 'APPROVAL_NOTICE_SENT')`);
        await queryRunner.query(`CREATE TABLE "registrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" uuid, "updatedBy" uuid, "userId" uuid NOT NULL, "referenceNumber" character varying, "status" "public"."registrations_status_enum" NOT NULL DEFAULT 'DRAFT', "currentStep" "public"."registrations_currentstep_enum" NOT NULL DEFAULT 'PERSONAL_DETAILS', "completedSteps" jsonb NOT NULL DEFAULT '[]', "engineeringDiscipline" "public"."registrations_engineeringdiscipline_enum", "applicationType" "public"."registrations_applicationtype_enum" NOT NULL DEFAULT 'NEW', "existingMembershipNumber" character varying, "registrationCategory" "public"."registrations_registrationcategory_enum", "appliedMembershipClass" character varying, "registeredWithStatutoryBoards" boolean NOT NULL DEFAULT false, "memberOfOtherInstitutions" boolean NOT NULL DEFAULT false, "otherInstitutions" jsonb NOT NULL DEFAULT '[]', "supportingDocumentUrl" character varying, "cvAttachment" character varying, "emailVerified" boolean NOT NULL DEFAULT false, "paymentCompleted" boolean NOT NULL DEFAULT false, "paymentId" uuid, "declarationAgreed" boolean NOT NULL DEFAULT false, "declarationSignature" character varying, "declarationDate" TIMESTAMP WITH TIME ZONE, "submittedAt" TIMESTAMP WITH TIME ZONE, "reviewStage" "public"."registrations_reviewstage_enum", "assignedEvaluatorId" uuid, "assignedAt" TIMESTAMP WITH TIME ZONE, "stageUpdatedAt" TIMESTAMP WITH TIME ZONE, "workflowDelayNotifiedAt" TIMESTAMP WITH TIME ZONE, "councilApprovedAt" TIMESTAMP WITH TIME ZONE, "approvalNoticeSentAt" TIMESTAMP WITH TIME ZONE, "reviewedBy" uuid, "reviewedAt" TIMESTAMP WITH TIME ZONE, "reviewComments" text, "rejectionReason" text, CONSTRAINT "UQ_b9f8e3b9af637793c3ba60e73ff" UNIQUE ("referenceNumber"), CONSTRAINT "PK_6013e724d7b22929da9cd7282d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_697b5c91986c7bdb776b3c1431" ON "registrations" ("referenceNumber") WHERE "referenceNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_f49b79edeb7c546d6d5fcaa750" ON "registrations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e5ae7aa55bb98b8b9dcbe32ca" ON "registrations" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."application_stage_history_fromstage_enum" AS ENUM('SECRETARIAT_REVIEW', 'EVALUATOR_REVIEW', 'SECRETARIAT_EVALUATOR_RECOMMENDATION', 'MPDC_REVIEW', 'SECRETARIAT_MPDC_RECOMMENDATION', 'COUNCIL_REVIEW', 'SECRETARIAT_COUNCIL_RECOMMENDATION', 'APPROVAL_NOTICE_SENT')`);
        await queryRunner.query(`CREATE TYPE "public"."application_stage_history_tostage_enum" AS ENUM('SECRETARIAT_REVIEW', 'EVALUATOR_REVIEW', 'SECRETARIAT_EVALUATOR_RECOMMENDATION', 'MPDC_REVIEW', 'SECRETARIAT_MPDC_RECOMMENDATION', 'COUNCIL_REVIEW', 'SECRETARIAT_COUNCIL_RECOMMENDATION', 'APPROVAL_NOTICE_SENT')`);
        await queryRunner.query(`CREATE TABLE "application_stage_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" uuid, "updatedBy" uuid, "registrationId" uuid NOT NULL, "fromStage" "public"."application_stage_history_fromstage_enum", "toStage" "public"."application_stage_history_tostage_enum" NOT NULL, "action" character varying(64) NOT NULL, "comments" text, "assignedEvaluatorId" uuid, CONSTRAINT "PK_5fc6de3bfc19895d9502ef25b32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc8691069d244f29cebe9a3cab" ON "application_stage_history" ("registrationId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymenttype_enum" AS ENUM('APPLICATION_FEE', 'MEMBERSHIP_FEE', 'EVENT_REGISTRATION', 'UPGRADE_FEE')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymentmethod_enum" AS ENUM('AIRTEL_MONEY', 'TIGO_PESA', 'HALOPESA', 'MPESA', 'SELCOM', 'DPO_BANK')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid, "paymentType" "public"."payments_paymenttype_enum" NOT NULL, "amount" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'TZS', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "paymentMethod" "public"."payments_paymentmethod_enum" NOT NULL, "description" character varying, "phoneNumber" character varying, "transactionRef" character varying, "mobileMoneyRef" character varying, "paymentUrl" character varying, "providerResponse" jsonb NOT NULL DEFAULT '{}', "metadata" jsonb NOT NULL DEFAULT '{}', "referenceId" uuid, "referenceType" character varying, "receiptNumber" character varying, "receiptUrl" character varying, "completedAt" TIMESTAMP WITH TIME ZONE, "errorMessage" text, "retryCount" integer NOT NULL DEFAULT '0', "lastRetryAt" TIMESTAMP WITH TIME ZONE, "idempotencyKey" character varying, CONSTRAINT "UQ_7d11b6414a612bd5a68bcc6b187" UNIQUE ("transactionRef"), CONSTRAINT "UQ_743b9fb1d2a059f2f7860418e4e" UNIQUE ("idempotencyKey"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6d38311ec5d479d19e58fea034" ON "payments" ("transactionRef") WHERE "transactionRef" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_b22829e26749c1c1b773506e5f" ON "payments" ("paymentType") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d35cb3c13a18e1ea1705b2817b" ON "payments" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('PAYMENT_REMINDER', 'EVENT_REMINDER', 'APPLICATION_UPDATE', 'APPLICATION_DELAY', 'MEMBERSHIP_EXPIRY', 'GENERAL_ANNOUNCEMENT', 'WELCOME', 'PASSWORD_RESET', 'EMAIL_VERIFICATION')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP WITH TIME ZONE, "actionUrl" character varying, "data" jsonb NOT NULL DEFAULT '{}', "sentVia" jsonb NOT NULL DEFAULT '[]', "emailSentAt" TIMESTAMP WITH TIME ZONE, "smsSentAt" TIMESTAMP WITH TIME ZONE, "pushSentAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_831a5a06f879fb0bebf8965871" ON "notifications" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ba28344602d583583b9ea1a50" ON "notifications" ("isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."membership_fees_membershipclass_enum" AS ENUM('GRADUATE', 'ASSOCIATE', 'MIET', 'CORPORATE', 'SENIOR', 'FELLOW', 'HONORARY')`);
        await queryRunner.query(`CREATE TYPE "public"."membership_fees_status_enum" AS ENUM('PENDING', 'PAID', 'OVERDUE', 'EXPIRING')`);
        await queryRunner.query(`CREATE TYPE "public"."membership_fees_paymentmethod_enum" AS ENUM('AIRTEL_MONEY', 'TIGO_PESA', 'HALOPESA', 'MPESA', 'SELCOM', 'DPO_BANK')`);
        await queryRunner.query(`CREATE TABLE "membership_fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "year" integer NOT NULL, "membershipClass" "public"."membership_fees_membershipclass_enum" NOT NULL, "amount" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'TZS', "status" "public"."membership_fees_status_enum" NOT NULL DEFAULT 'PENDING', "dueDate" date NOT NULL, "paidAt" TIMESTAMP WITH TIME ZONE, "paymentMethod" "public"."membership_fees_paymentmethod_enum", "paymentId" uuid, "transactionRef" character varying, "receiptNumber" character varying, "receiptUrl" character varying, "notes" text, "remindersSent" integer NOT NULL DEFAULT '0', "lastReminderAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_0be8a43d83d22ab5d59803d5798" UNIQUE ("receiptNumber"), CONSTRAINT "PK_6d45a7c6c9a60f15672f3023536" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ce581518b9cfde951416d65cc3" ON "membership_fees" ("userId", "year") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8c7e5b27ce560b0eff1b67595" ON "membership_fees" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b47d14dfa135266d50ce8eea28" ON "membership_fees" ("year") `);
        await queryRunner.query(`CREATE INDEX "IDX_0147ea3e538215294e245140cc" ON "membership_fees" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."event_registrations_attendeetype_enum" AS ENUM('MEMBER', 'NON_MEMBER', 'GUEST', 'SPEAKER', 'ORGANIZER')`);
        await queryRunner.query(`CREATE TYPE "public"."event_registrations_status_enum" AS ENUM('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'ATTENDED', 'NO_SHOW', 'EXPIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."event_registrations_paymentmethod_enum" AS ENUM('AIRTEL_MONEY', 'TIGO_PESA', 'HALOPESA', 'MPESA', 'SELCOM', 'DPO_BANK')`);
        await queryRunner.query(`CREATE TYPE "public"."event_registrations_refundstatus_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "event_registrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "eventId" uuid NOT NULL, "userId" uuid NOT NULL, "attendeeType" "public"."event_registrations_attendeetype_enum" NOT NULL DEFAULT 'MEMBER', "status" "public"."event_registrations_status_enum" NOT NULL DEFAULT 'PENDING_PAYMENT', "specialRequirements" text, "amountPaid" integer NOT NULL DEFAULT '0', "paymentMethod" "public"."event_registrations_paymentmethod_enum", "paymentId" uuid, "transactionRef" character varying, "ticketNumber" character varying, "qrCodeUrl" character varying, "confirmedAt" TIMESTAMP WITH TIME ZONE, "attendedAt" TIMESTAMP WITH TIME ZONE, "checkInNotes" text, "cancellationReason" text, "cancelledAt" TIMESTAMP WITH TIME ZONE, "refundAmount" integer NOT NULL DEFAULT '0', "refundStatus" "public"."event_registrations_refundstatus_enum", "certificateUrl" character varying, "certificateCode" character varying, "feedbackRating" integer, "feedbackComment" text, "paymentExpiresAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_ac0d4b642e0f014388cd1ca67c5" UNIQUE ("ticketNumber"), CONSTRAINT "PK_953d3b862c2487289a92b2356e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_61ec423ed5280af08b42f1adf6" ON "event_registrations" ("ticketNumber") WHERE "ticketNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b308df020159fd5c476ace931d" ON "event_registrations" ("eventId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a072346484fe1d7ee0fb9dfaa" ON "event_registrations" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4e6dce237a527e4515f3d430f" ON "event_registrations" ("eventId") `);
        await queryRunner.query(`CREATE TYPE "public"."events_category_enum" AS ENUM('CPD_COURSE', 'CONFERENCE', 'WORKSHOP', 'SEMINAR', 'ONLINE_SEMINAR', 'AGM', 'NETWORKING')`);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" uuid, "updatedBy" uuid, "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "category" "public"."events_category_enum" NOT NULL, "startDate" date NOT NULL, "endDate" date, "startTime" character varying NOT NULL, "endTime" character varying NOT NULL, "location" character varying, "isOnline" boolean NOT NULL DEFAULT false, "onlineUrl" character varying, "guestOfHonor" character varying, "speakers" jsonb NOT NULL DEFAULT '[]', "agenda" jsonb NOT NULL DEFAULT '[]', "coverImage" character varying, "images" jsonb NOT NULL DEFAULT '[]', "registrationDeadline" date, "registrationFee" integer NOT NULL DEFAULT '0', "cpdPoints" integer NOT NULL DEFAULT '0', "maxParticipants" integer, "requirements" jsonb NOT NULL DEFAULT '[]', "organizer" jsonb NOT NULL DEFAULT '{}', "isPublished" boolean NOT NULL DEFAULT false, "registrationOpen" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_05bd884c03d3f424e2204bd14cd" UNIQUE ("slug"), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_05bd884c03d3f424e2204bd14c" ON "events" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_f20503eb78cfdac5f8eda342c8" ON "events" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_89790086fbc0aa80d8cf577285" ON "events" ("startDate") `);
        await queryRunner.query(`CREATE TYPE "public"."guest_registrations_status_enum" AS ENUM('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'ATTENDED', 'NO_SHOW', 'EXPIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."guest_registrations_paymentmethod_enum" AS ENUM('AIRTEL_MONEY', 'TIGO_PESA', 'HALOPESA', 'MPESA', 'SELCOM', 'DPO_BANK')`);
        await queryRunner.query(`CREATE TYPE "public"."guest_registrations_paymentstatus_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "guest_registrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "eventId" uuid NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "organization" character varying, "position" character varying, "nationality" character varying, "status" "public"."guest_registrations_status_enum" NOT NULL DEFAULT 'PENDING_PAYMENT', "specialRequirements" text, "ticketNumber" character varying, "qrCodeUrl" character varying, "controlNumber" character varying, "amountPaid" integer NOT NULL DEFAULT '0', "paymentMethod" "public"."guest_registrations_paymentmethod_enum", "paymentId" uuid, "transactionRef" character varying, "paymentStatus" "public"."guest_registrations_paymentstatus_enum" NOT NULL DEFAULT 'PENDING', "receiptNumber" character varying, "checkedInAt" TIMESTAMP WITH TIME ZONE, "checkedInBy" uuid, "checkedOutAt" TIMESTAMP WITH TIME ZONE, "certificateUrl" character varying, "certificateCode" character varying, "certificateGeneratedAt" TIMESTAMP WITH TIME ZONE, "nameTagGenerated" boolean NOT NULL DEFAULT false, "nameTagUrl" character varying, CONSTRAINT "PK_10957f4576555c1886ec3eabf50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9912d8014d560541a9cb830457" ON "guest_registrations" ("controlNumber") WHERE "controlNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cba84f87699061ea3db0d482fe" ON "guest_registrations" ("ticketNumber") WHERE "ticketNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_09eb7ab85e2a1707b38c1aa37b" ON "guest_registrations" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1e7533aac9df7dbcb33bed71f" ON "guest_registrations" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."development_fees_paymentmethod_enum" AS ENUM('AIRTEL_MONEY', 'TIGO_PESA', 'HALOPESA', 'MPESA', 'SELCOM', 'DPO_BANK')`);
        await queryRunner.query(`CREATE TYPE "public"."development_fees_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "development_fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "organization" character varying, "purpose" character varying NOT NULL, "amount" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'TZS', "notes" text, "controlNumber" character varying, "paymentMethod" "public"."development_fees_paymentmethod_enum", "paymentId" uuid, "transactionRef" character varying, "status" "public"."development_fees_status_enum" NOT NULL DEFAULT 'PENDING', "paidAt" TIMESTAMP WITH TIME ZONE, "receiptNumber" character varying, "receiptUrl" character varying, CONSTRAINT "PK_8e749463c4c61ebb2f543ef77ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_37a02ff51bcee9e4a80a1ac930" ON "development_fees" ("controlNumber") WHERE "controlNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_66158fd743969aa8686a095e88" ON "development_fees" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_4182bc2347fb99795ff7ff8efa" ON "development_fees" ("email") `);
        await queryRunner.query(`CREATE TABLE "communication_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" uuid, "updatedBy" uuid, "name" character varying NOT NULL, "type" character varying NOT NULL, "subject" character varying, "body" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_ca5cd6c5ee3127e345e9d30a719" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d1ae1c4fcc7d234b6a7aa3666" ON "communication_templates" ("type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4d0688eac5e8a496dff9a553d7" ON "communication_templates" ("name") `);
        await queryRunner.query(`CREATE TABLE "communication_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" uuid, "updatedBy" uuid, "createdById" uuid, "type" character varying NOT NULL, "target" character varying NOT NULL, "groupId" uuid, "subject" character varying, "message" text NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "recipientCount" integer NOT NULL DEFAULT '0', "successfulCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "sentAt" TIMESTAMP WITH TIME ZONE, "errorSummary" text, CONSTRAINT "PK_9aad48c5013416feccdfb1f4352" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_83b6d05d88a0a4203c30f88464" ON "communication_messages" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_899fc8aa7b802087c10b10b2ba" ON "communication_messages" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bb694c81d9b2e223f3c371e1f" ON "communication_messages" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5943c801b4a1e261136a72b99f" ON "communication_messages" ("target") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cce113e2aa04bdd81e2534da6" ON "communication_messages" ("type") `);
        await queryRunner.query(`CREATE TABLE "communication_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" uuid, "updatedBy" uuid, "messageId" uuid NOT NULL, "userId" uuid, "recipient" character varying NOT NULL, "channel" character varying NOT NULL, "status" character varying NOT NULL, "error" text, "sentAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cd4423d6f734d4fbb00bed783b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff8eb8be9e1eedaabc565c6f90" ON "communication_deliveries" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2359fa449512de02a7a657ea58" ON "communication_deliveries" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb8a1f1e00b06cc00149e5faa7" ON "communication_deliveries" ("messageId") `);
        await queryRunner.query(`CREATE TABLE "system_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" text NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b1b5bc664526d375c94ce9ad43d" UNIQUE ("key"), CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_8e4aa9c0fec118f1c8a6edd309c" FOREIGN KEY ("membershipCategoryId") REFERENCES "membership_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upgrade_rules" ADD CONSTRAINT "FK_30906b66cb1af7a9a0c91df1ffe" FOREIGN KEY ("fromCategoryId") REFERENCES "membership_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upgrade_rules" ADD CONSTRAINT "FK_b58b2cf38367f9fe31edd8ddc5c" FOREIGN KEY ("toCategoryId") REFERENCES "membership_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upgrade_applications" ADD CONSTRAINT "FK_6185692b04b1557a7dae5460454" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upgrade_applications" ADD CONSTRAINT "FK_8f20db0bed145518e8fbd4eba5e" FOREIGN KEY ("fromCategoryId") REFERENCES "membership_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upgrade_applications" ADD CONSTRAINT "FK_96513ff83ebb6f15d30aaa4b520" FOREIGN KEY ("toCategoryId") REFERENCES "membership_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upgrade_applications" ADD CONSTRAINT "FK_449a11152b594b430d43039bbe1" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registration_experiences" ADD CONSTRAINT "FK_a77dcf24eb60816939bd282bcda" FOREIGN KEY ("registrationId") REFERENCES "registrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registration_educations" ADD CONSTRAINT "FK_60054d4846fde3cde29f4fbf45b" FOREIGN KEY ("registrationId") REFERENCES "registrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registration_educations" ADD CONSTRAINT "FK_33761889fee1650f36fecd99e6a" FOREIGN KEY ("institutionId") REFERENCES "engineering_institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registration_documents" ADD CONSTRAINT "FK_11dfe2648f9819f117d0f516ae9" FOREIGN KEY ("registrationId") REFERENCES "registrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registration_references" ADD CONSTRAINT "FK_40dbbc2643e52cbbf3a8a3bb11a" FOREIGN KEY ("registrationId") REFERENCES "registrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registrations" ADD CONSTRAINT "FK_7e5ae7aa55bb98b8b9dcbe32ca3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_stage_history" ADD CONSTRAINT "FK_03e8969f88c5e21ff90e2cc7014" FOREIGN KEY ("registrationId") REFERENCES "registrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_fees" ADD CONSTRAINT "FK_0147ea3e538215294e245140ccd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_registrations" ADD CONSTRAINT "FK_e4e6dce237a527e4515f3d430f1" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_registrations" ADD CONSTRAINT "FK_7a072346484fe1d7ee0fb9dfaa8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guest_registrations" ADD CONSTRAINT "FK_ca400da8b14e58743abd47f8cc0" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication_messages" ADD CONSTRAINT "FK_6e22432747646296d517c97405f" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication_messages" ADD CONSTRAINT "FK_899fc8aa7b802087c10b10b2ba9" FOREIGN KEY ("groupId") REFERENCES "membership_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication_deliveries" ADD CONSTRAINT "FK_eb8a1f1e00b06cc00149e5faa71" FOREIGN KEY ("messageId") REFERENCES "communication_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication_deliveries" ADD CONSTRAINT "FK_2359fa449512de02a7a657ea583" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "communication_deliveries" DROP CONSTRAINT "FK_2359fa449512de02a7a657ea583"`);
        await queryRunner.query(`ALTER TABLE "communication_deliveries" DROP CONSTRAINT "FK_eb8a1f1e00b06cc00149e5faa71"`);
        await queryRunner.query(`ALTER TABLE "communication_messages" DROP CONSTRAINT "FK_899fc8aa7b802087c10b10b2ba9"`);
        await queryRunner.query(`ALTER TABLE "communication_messages" DROP CONSTRAINT "FK_6e22432747646296d517c97405f"`);
        await queryRunner.query(`ALTER TABLE "guest_registrations" DROP CONSTRAINT "FK_ca400da8b14e58743abd47f8cc0"`);
        await queryRunner.query(`ALTER TABLE "event_registrations" DROP CONSTRAINT "FK_7a072346484fe1d7ee0fb9dfaa8"`);
        await queryRunner.query(`ALTER TABLE "event_registrations" DROP CONSTRAINT "FK_e4e6dce237a527e4515f3d430f1"`);
        await queryRunner.query(`ALTER TABLE "membership_fees" DROP CONSTRAINT "FK_0147ea3e538215294e245140ccd"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`ALTER TABLE "application_stage_history" DROP CONSTRAINT "FK_03e8969f88c5e21ff90e2cc7014"`);
        await queryRunner.query(`ALTER TABLE "registrations" DROP CONSTRAINT "FK_7e5ae7aa55bb98b8b9dcbe32ca3"`);
        await queryRunner.query(`ALTER TABLE "registration_references" DROP CONSTRAINT "FK_40dbbc2643e52cbbf3a8a3bb11a"`);
        await queryRunner.query(`ALTER TABLE "registration_documents" DROP CONSTRAINT "FK_11dfe2648f9819f117d0f516ae9"`);
        await queryRunner.query(`ALTER TABLE "registration_educations" DROP CONSTRAINT "FK_33761889fee1650f36fecd99e6a"`);
        await queryRunner.query(`ALTER TABLE "registration_educations" DROP CONSTRAINT "FK_60054d4846fde3cde29f4fbf45b"`);
        await queryRunner.query(`ALTER TABLE "registration_experiences" DROP CONSTRAINT "FK_a77dcf24eb60816939bd282bcda"`);
        await queryRunner.query(`ALTER TABLE "upgrade_applications" DROP CONSTRAINT "FK_449a11152b594b430d43039bbe1"`);
        await queryRunner.query(`ALTER TABLE "upgrade_applications" DROP CONSTRAINT "FK_96513ff83ebb6f15d30aaa4b520"`);
        await queryRunner.query(`ALTER TABLE "upgrade_applications" DROP CONSTRAINT "FK_8f20db0bed145518e8fbd4eba5e"`);
        await queryRunner.query(`ALTER TABLE "upgrade_applications" DROP CONSTRAINT "FK_6185692b04b1557a7dae5460454"`);
        await queryRunner.query(`ALTER TABLE "upgrade_rules" DROP CONSTRAINT "FK_b58b2cf38367f9fe31edd8ddc5c"`);
        await queryRunner.query(`ALTER TABLE "upgrade_rules" DROP CONSTRAINT "FK_30906b66cb1af7a9a0c91df1ffe"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_8e4aa9c0fec118f1c8a6edd309c"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb8a1f1e00b06cc00149e5faa7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2359fa449512de02a7a657ea58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff8eb8be9e1eedaabc565c6f90"`);
        await queryRunner.query(`DROP TABLE "communication_deliveries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cce113e2aa04bdd81e2534da6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5943c801b4a1e261136a72b99f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bb694c81d9b2e223f3c371e1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_899fc8aa7b802087c10b10b2ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83b6d05d88a0a4203c30f88464"`);
        await queryRunner.query(`DROP TABLE "communication_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d0688eac5e8a496dff9a553d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d1ae1c4fcc7d234b6a7aa3666"`);
        await queryRunner.query(`DROP TABLE "communication_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4182bc2347fb99795ff7ff8efa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66158fd743969aa8686a095e88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37a02ff51bcee9e4a80a1ac930"`);
        await queryRunner.query(`DROP TABLE "development_fees"`);
        await queryRunner.query(`DROP TYPE "public"."development_fees_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."development_fees_paymentmethod_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1e7533aac9df7dbcb33bed71f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09eb7ab85e2a1707b38c1aa37b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cba84f87699061ea3db0d482fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9912d8014d560541a9cb830457"`);
        await queryRunner.query(`DROP TABLE "guest_registrations"`);
        await queryRunner.query(`DROP TYPE "public"."guest_registrations_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."guest_registrations_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."guest_registrations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89790086fbc0aa80d8cf577285"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f20503eb78cfdac5f8eda342c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05bd884c03d3f424e2204bd14c"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TYPE "public"."events_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4e6dce237a527e4515f3d430f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a072346484fe1d7ee0fb9dfaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b308df020159fd5c476ace931d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61ec423ed5280af08b42f1adf6"`);
        await queryRunner.query(`DROP TABLE "event_registrations"`);
        await queryRunner.query(`DROP TYPE "public"."event_registrations_refundstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."event_registrations_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."event_registrations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."event_registrations_attendeetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0147ea3e538215294e245140cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b47d14dfa135266d50ce8eea28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8c7e5b27ce560b0eff1b67595"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce581518b9cfde951416d65cc3"`);
        await queryRunner.query(`DROP TABLE "membership_fees"`);
        await queryRunner.query(`DROP TYPE "public"."membership_fees_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."membership_fees_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."membership_fees_membershipclass_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ba28344602d583583b9ea1a50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_831a5a06f879fb0bebf8965871"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d35cb3c13a18e1ea1705b2817b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b22829e26749c1c1b773506e5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d38311ec5d479d19e58fea034"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc8691069d244f29cebe9a3cab"`);
        await queryRunner.query(`DROP TABLE "application_stage_history"`);
        await queryRunner.query(`DROP TYPE "public"."application_stage_history_tostage_enum"`);
        await queryRunner.query(`DROP TYPE "public"."application_stage_history_fromstage_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e5ae7aa55bb98b8b9dcbe32ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f49b79edeb7c546d6d5fcaa750"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_697b5c91986c7bdb776b3c1431"`);
        await queryRunner.query(`DROP TABLE "registrations"`);
        await queryRunner.query(`DROP TYPE "public"."registrations_reviewstage_enum"`);
        await queryRunner.query(`DROP TYPE "public"."registrations_registrationcategory_enum"`);
        await queryRunner.query(`DROP TYPE "public"."registrations_applicationtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."registrations_engineeringdiscipline_enum"`);
        await queryRunner.query(`DROP TYPE "public"."registrations_currentstep_enum"`);
        await queryRunner.query(`DROP TYPE "public"."registrations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40dbbc2643e52cbbf3a8a3bb11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9f002a1c325777ec374a11643"`);
        await queryRunner.query(`DROP TABLE "registration_references"`);
        await queryRunner.query(`DROP TYPE "public"."registration_references_referencetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11dfe2648f9819f117d0f516ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb3295a550bc5c23d0a9645663"`);
        await queryRunner.query(`DROP TABLE "registration_documents"`);
        await queryRunner.query(`DROP TYPE "public"."registration_documents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."registration_documents_documenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60054d4846fde3cde29f4fbf45"`);
        await queryRunner.query(`DROP TABLE "registration_educations"`);
        await queryRunner.query(`DROP TABLE "engineering_institutions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a77dcf24eb60816939bd282bcd"`);
        await queryRunner.query(`DROP TABLE "registration_experiences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6185692b04b1557a7dae546045"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f145ea19883c1a2d2f015b67f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f20db0bed145518e8fbd4eba5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96513ff83ebb6f15d30aaa4b52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8a037f603d080132ca4a6019d"`);
        await queryRunner.query(`DROP TABLE "upgrade_applications"`);
        await queryRunner.query(`DROP TYPE "public"."upgrade_applications_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30906b66cb1af7a9a0c91df1ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b58b2cf38367f9fe31edd8ddc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df14ec8f89f337a5416fa7f9c4"`);
        await queryRunner.query(`DROP TABLE "upgrade_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48054969958a2041d65fca2c1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e3d0240b49c40521aaeb95329"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e4aa9c0fec118f1c8a6edd309"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_engineeringdiscipline_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_membershipstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_membershipclass_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_title_enum"`);
        await queryRunner.query(`DROP TABLE "membership_categories"`);
    }

}
